spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grouporder
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create

#  flyway:
#    baseline-on-migrate: true
#    locations: classpath:db/migration
server.port: 8080